// PRIVATE original notes, grounded in HANDOFF-REPORT §3, the newer PIPELINE Q&A,
// and Josh's requests. No invented memories, specific artworks or song meanings.
import { createHash } from "node:crypto";

const groups = [
  { theme: "art", label: "for your artist heart", notes: [
    "a drawing starts as something nobody else can see, and u give it a place in the world. that is a very cool thing to be able to do.",
    "ur sketchbook doesn't have to look like anybody else's. the person holding the pencil is the whole reason it gets to be different.",
    "digital art and traditional drawing? u really looked at one way of making things and decided u wanted more. i love that curiosity.",
    "a rough sketch still contains a decision only u would make. even the unfinished pages have a little bit of ur imagination in them.",
    "u don't owe the internet a finished piece every time u draw. some pictures can exist purely because making them felt nice.",
    "there's room for the careful drawing and the ridiculous little doodle. ur art gets to have a sense of humour too.",
    "procreate has a lot of brushes. it still needs u to decide what happens on the page. the interesting part was never just the app.",
    "a favourite character through ur imagination becomes a slightly different little world. that's such a lovely way to love something.",
    "a page doesn't have to be impressive to be worth keeping. sometimes it can just remember what u felt like making that day.",
    "ur next drawing doesn't need to prove that the last good one wasn't an accident. u can just make the next drawing.",
    "colour mixing is basically permission to change ur mind beautifully. a little more pink? a little more purple? entirely ur business.",
    "trying a different style doesn't mean abandoning ur own. u get to collect possibilities without signing a lifelong contract with one brush.",
    "if a drawing isn't going where u wanted, u can leave it for a bit. the page will not file a complaint.",
    "the tiny drawing in the corner counts. the five-minute doodle counts. art doesn't become real only when it takes all afternoon.",
    "somebody else being good at art doesn't take a single colour out of ur palette. there is room for what u make.",
    "u can be proud of one little detail in a piece u aren't sure about. liking part of it is allowed.",
    "a new sketchbook page is an invitation, not an exam. u don't have to get the opening line right.",
    "keep a drawing for future u sometimes. not to grade the progress. just to remember what ur imagination was interested in.",
    "that mix of drawing, costumes and music gives u so many places to find an idea. ur interests are very good company for each other.",
    "tiny artist reminder: save the file. then give ur eyes a moment away from the screen. ur idea can wait for u.",
  ]},
  { theme: "cosplay", label: "for the maker in u", notes: [
    "maomao, miku and lynette. that's a lovely little cast of characters to have brought into ur own world through cosplay.",
    "wig styling is such a specific kind of patience. u take a pile of possibilities and persuade it to become a character.",
    "a cosplay is made from so many decisions people might never notice. those little decisions still deserve some credit.",
    "u can love a character without copying every last detail perfectly. ur take gets to exist too.",
    "the person behind the costume matters just as much as the costume. kiriya remains the best part of a kiriya cosplay.",
    "snow miku, sakura miku, all those versions on the wishlist… a very respectable excuse to keep imagining new colours.",
    "cosplay can be a project, a performance, a craft and a silly afternoon. u don't have to pick the most serious version every time.",
    "one tricky wig section doesn't get to erase the skills u already have. even an experienced cosplayer is allowed a stubborn bit of hair.",
    "u can put a project down without breaking up with it. the fabric will still be fabric tomorrow.",
    "the reveal is lovely, but the making deserves affection too. all those small choices are part of the magic.",
    "lynette, maomao and miku each give u a different world to play in. ur imagination has excellent travel arrangements.",
    "u don't have to wait for a whole costume to be finished before enjoying one part of it. a detail can have its own little celebration.",
    "a cosplay wishlist is allowed to be a wishlist. it doesn't have to become a deadline wearing a cute outfit.",
    "making something wearable out of an idea is a very particular talent. u deserve to remember that when the fiddly bits get annoying.",
    "a reference picture is there to help u, not stand over ur shoulder with a clipboard.",
    "there's a lot to admire about someone who enjoys becoming part of the worlds they love. u don't just watch; u make things too.",
    "a costume can fit ur comfort as well as the character. being able to enjoy wearing it is part of the design.",
    "wig break reminder: unclench the hand holding the comb. a moment off is allowed, even if the strand is being personally difficult.",
    "u can ask for a second opinion and still trust ur own taste. both things can happen in the same project.",
    "the next character on ur wishlist can wait until u actually feel excited about making it. excitement is a nicer starting point than obligation.",
  ]},
  { theme: "ballet", label: "a little bow for u", notes: [
    "ballet is one of those things that can look effortless because somebody worked hard. the effort behind it deserves to be seen too.",
    "u collect skills that ask for patience. ballet, drawing, wig styling. there's something very lovely about being willing to learn difficult things.",
    "a practice day doesn't have to become a story about being brilliant or terrible. sometimes it can just be a practice day.",
    "u are allowed to enjoy dancing without turning every movement into a verdict about urself.",
    "there's creativity in movement too. not every part of ur imagination needs a page to live on.",
    "one wobbly moment doesn't get to narrate the whole lesson. it was one moment, not ur biography.",
    "progress can be quiet enough that u miss it while looking for something dramatic. the small things still belong to u.",
    "u can admire another dancer without shrinking the space ur own dancing takes up.",
    "being proud of learning something is allowed before u can do it perfectly. otherwise pride would have a very silly entry requirement.",
    "ballet and cosplay and art. ur hobbies have range, kiriya. the casting department is impressed.",
    "the music doesn't need u to punish urself for a missed beat. there's another moment to join it.",
    "a difficult skill can still be something u love on the days it feels difficult. those feelings aren't cancelling each other out.",
    "rest is allowed to be part of a day that includes dancing. u don't have to fill every spare minute with practice.",
    "u can carry the joy of a good movement without demanding that the next one be even better.",
    "some days the nicest dance is just moving a little to a song u love. no audience, no score, no explanation.",
    "being a beginner at one thing doesn't delete being experienced at another. u get to have different chapters open at once.",
    "a little applause for the patience it takes to repeat something while learning. the quiet attempts deserve a sound too.",
    "ur worth doesn't go up when practice goes well or down when it doesn't. the person having the lesson stays worth caring about.",
    "u don't have to make a hard thing look easy for everyone else. effort isn't embarrassing.",
    "after a busy day of making or moving, let the next thing be something gentle. a song, a seat, a moment with no assignment.",
  ]},
  { theme: "music", label: "a song-sized bit of love", notes: [
    "a favourite song doesn't need a sophisticated explanation. sometimes 'it makes me happy' is the entire review, and it's a good one.",
    "miku, rin and len have a place in ur world because u love them. liking something wholeheartedly is a sweet thing about u.",
    "ur playlist is allowed to go from bright and silly to an entire rin-and-len story. emotional range, excellent casting.",
    "u can sing along for the joy of it. every song doesn't need to secretly become an audition.",
    "having a song on repeat can be like keeping a little familiar light on. if it feels good, enjoy the light.",
    "a song that matters to u doesn't have to matter to everybody. the private little connection is enough.",
    "ur singing belongs to u before it belongs to anyone listening. there's room for a version that's just for fun.",
    "classics and new songs can share a playlist. ur old favourites aren't jealous. probably. miku has a busy schedule.",
    "u get to find different things in the same song on different days. that's one of the lovely parts of listening again.",
    "a little music reminder: u can pause the song, answer nobody and just sit for a moment. silence is allowed in the playlist too.",
    "the part where a song makes u want to draw something? two of ur favourite worlds saying hello.",
    "liking a voice, a melody or a tiny instrumental bit is reason enough to keep a song around. ur ears get a vote.",
    "a rough singing day isn't a reason to be unkind to the person singing. u still deserve to enjoy music.",
    "u don't have to know every fact about a voicebank to love the songs. fandom is not an entrance exam.",
    "miku leads, rin and len follow, and there's still room for more voices. ur music corner has a very generous guest list.",
    "a new song can be a little adventure that only asks a few minutes of u. no packing required.",
    "a song can remind u of a character, a colour, or absolutely nothing explainable. ur imagination doesn't owe anybody footnotes.",
    "u don't have to turn every song u like into something productive. listening is already doing the enjoyable part.",
    "the best song for right now is allowed to be the familiar one. novelty does not get automatic custody of the aux.",
    "if u feel like sharing a song, that's a lovely little window into what u enjoy. if u keep it to urself, it's still yours.",
  ]},
  { theme: "fandom", label: "for all ur favourite worlds", notes: [
    "the way u make room for favourite characters, songs and little details is lovely. caring about things gives ur world so much colour.",
    "maomao has herbs. u have a whole collection of interests. the shared talent is finding something fascinating and really caring about it.",
    "u can enjoy frieren or witch hat atelier without immediately making a project about it. the imagination can have a day off from deliverables.",
    "project sekai, drawing, cosplay, vocaloid. ur favourite things have a lot of lovely doors between them.",
    "ur favourite character can change, multiply or stay exactly the same. there is no loyalty contract hiding in the merch packaging.",
    "being excited about a tiny detail in a favourite world is a perfectly good use of excitement.",
    "there's something sweet about how a character can become a drawing idea, a costume idea or just a reason to smile.",
    "u don't have to be the most knowledgeable person in a fandom to deserve a happy little corner in it.",
    "wonderlands×showtime, vivid bad squad, leo/need… ur music world has room for more than one kind of energy. so do u.",
    "liking several worlds doesn't make ur love for any one of them less real. affection is not a storage limit.",
    "a favourite character can just be comforting company in a picture. they don't have to teach u a life lesson every time.",
    "that 'wait, look at this' feeling when something matches ur interests is a lovely part of being curious. keep a little room for it.",
    "a tiny badge or picture can carry a lot of happiness. the size of the thing doesn't decide how much it gets to matter.",
    "u can admire an outfit in a game simply because the design is cool. no ten-page defence of the colour palette required.",
    "ur love for vocaloid doesn't need to age out. things that bring u joy don't come with an expiry sticker.",
    "a familiar character on a difficult day can be a small kind thing. small kind things are worth keeping around.",
    "having lots of interests means there are lots of ways for a day to surprise u pleasantly. that's a nice thing to have in ur world.",
    "minecraft gets the joke corner, miku gets the music corner, maomao gets the herbs. u get the comfortable seat in the middle.",
    "u don't need a new purchase to prove u love a character. enjoying what u already have counts just as much.",
    "the best part of a favourite world is getting to decide what u love about it. ur little list doesn't need to match anyone else's.",
  ]},
  { theme: "kindness", label: "something lovely about u", notes: [
    "kind and sassy in the same person is an excellent combination. a soft heart with commentary. honestly, lovely casting.",
    "josh described u as caring. that is such a lovely thing for someone to notice and want to build a whole little world around.",
    "ur kindness deserves some kindness back. u don't have to be the only person doing the looking after.",
    "animals loving u is a very sweet detail in the story of who u are. a tiny, furry character reference.",
    "making people happier is a lovely thing about u. u aren't required to do it every minute to keep being loved.",
    "a caring person is still allowed to need space. having a kind heart doesn't mean leaving the door open all day.",
    "u can say no gently, awkwardly or without a whole essay. ur boundaries don't have to be beautifully written to count.",
    "there is something special about being both passionate and caring. u have room in ur world for things and for people.",
    "being kind doesn't mean every feeling u have must be nice and tidy. u get the full set of human emotions too.",
    "the care u give isn't worth less because it happens quietly. not every lovely thing arrives with a soundtrack.",
    "u deserve friends who are interested when u talk about what u love. attention should get to travel both ways.",
    "ur caring side isn't a resource everyone else gets to spend. a little of it is allowed to stay with u.",
    "someone thought about what makes u special and wrote down ur kindness. that belongs on the list beside every impressive skill.",
    "u don't have to be useful to be good company. being there as urself is allowed to be enough.",
    "a soft heart can have a very firm 'absolutely not'. those two things can be excellent neighbours.",
    "u deserve the kind of understanding u try to give other people, including on the days when ur words come out a bit messy.",
    "making someone laugh and caring about them are both ways of making a day a little less lonely. ur humour and kindness go nicely together.",
    "u can receive a compliment without producing one in return immediately. let this little nice thing stay with u for a second.",
    "being caring is lovely. being cared for is not something u have to earn by being even more caring first.",
    "a small reminder for ur kind soul: include urself when deciding who deserves patience today.",
  ]},
  { theme: "humour", label: "a little smile for u", notes: [
    "ur sense of humour made it into the official list of things josh loves about u. very serious paperwork. extremely unserious subject.",
    "the sass is part of the charm. this jar has reviewed the evidence and will not be asking u to remove it.",
    "drawing, ballet, singing, wig styling. ur hobbies read like several talented people sharing one very cute account.",
    "this is a tiny compliment with no homework attached. suspiciously reasonable terms and conditions, i know.",
    "ur hobbies have hobbies. somewhere, a perfectly ordinary pencil is wondering how it ended up in such an interesting household.",
    "u are permitted to be a little ridiculous about things u enjoy. the joy committee has signed the form.",
    "a jar full of compliments and u chose another one. excellent. finally, someone using this website's resources correctly.",
    "ur favourite colours being purple and pink makes this jar feel very well dressed. thank u for the creative direction.",
    "maomao can investigate the mystery. miku can handle the soundtrack. u can have the snacks and a little peace.",
    "this note would like to formally recognise ur range: soft-hearted, talented, and capable of commentary. a versatile production.",
    "u don't have to be mysterious and cool all the time. getting excited about a favourite character is a perfectly acceptable plot twist.",
    "a tiny award for having interests with this much personality. the trophy is imaginary because i spent the budget on being a jar.",
    "if ur favourite things had a group chat, the notifications would be spectacular. miku is sending a voice note. maomao is asking about a leaf.",
    "ur imagination has several tabs open. none of them needs to become a deadline today.",
    "being a bit sassy doesn't cancel being sweet. it just means the cupcake has opinions.",
    "u can take a compliment without arguing with the jar. it has no debate club experience and only one point to make: u matter.",
    "not every thought needs to become a productive activity. some can just run around ur head wearing a tiny miku wig.",
    "today's extremely biased review: interesting taste, lovely heart, excellent potential for a funny remark. would leave another note.",
    "u get another little bit of affection. there is no secret quiz after this. the jar is academically unambitious.",
    "the note jar would like a break from being shaken. unfortunately for the jar, cheering u up is the job.",
  ]},
  { theme: "style", label: "entirely ur kind of lovely", notes: [
    "purple, pink, a little dark detail. ur favourite colours already make such a lovely little world together.",
    "sweet outfits and skater streetwear can both belong to u. ur wardrobe doesn't have to elect one permanent spokesperson.",
    "u don't have to explain a look beyond 'i like it'. enjoying how u dress is a complete enough reason.",
    "there are lots of ways to look like urself. u get to pick a different one when u feel like it.",
    "a tiny accessory can be the whole point of an outfit. little details are allowed to have big personalities.",
    "josh put 'pretty' on the list about u. just thought that little fact deserved its own piece of paper.",
    "ur smile deserves a compliment that doesn't immediately turn into a joke. so here's one: it's a lovely thing to have in the world.",
    "feeling comfortable in ur clothes matters. an outfit that lets u enjoy the day has done something very good.",
    "u can like a dramatic look and still choose the comfortable one today. taste doesn't disappear when u take a rest.",
    "ur style gets to change with u. the old favourite and the new idea can both keep a place in the wardrobe.",
    "a pink detail in a darker outfit is such a fun little conversation between colours. ur favourites play well together.",
    "u don't need a special occasion to enjoy a favourite little thing u own. an ordinary day can be the occasion.",
    "looking like a character u love can be joyful. looking like kiriya, without a costume, deserves affection too.",
    "some days a favourite colour is enough of a plan. purple has never asked for a project brief.",
    "u can admire somebody else's style without making ur own smaller. clothes are not a competition for one available personality.",
    "a nice smile, a kind heart and a very specific collection of interests. there's more than one lovely thing to notice about u.",
    "the way u choose what belongs in ur world is part of its charm. not everything needs to be fashionable to be a favourite.",
    "ur wishlist can be a place for dreaming, not a list of things missing from u. u are already a whole person.",
    "a look can be cute because it feels like u. it doesn't need unanimous approval from the imaginary fashion council.",
    "u deserve to feel at home in whatever version of urself shows up today. this little corner has room for all of them.",
  ]},
  { theme: "rest", label: "a small caring reminder", notes: [
    "if ur water is nearby, this is a tiny reminder that it exists. no dramatic life advice, just a sip if u want one.",
    "save the drawing before u get comfortable. future u deserves the file as well as the nice idea.",
    "u can put the screen down for a moment and look at something farther away. the little worlds inside it will wait.",
    "if the song has ended and ur shoulders are still up by ur ears, let them come down a little. no need to hold up the whole soundtrack.",
    "an unfinished costume isn't going to stop being interesting because u went to sleep. rest can have its turn.",
    "if a meal slipped past while u were busy, there's room to pause for one. the project doesn't get every appointment on the calendar.",
    "u can leave a little note for tomorrow's project instead of finishing the whole thing tonight. 'start here' is a valid ending.",
    "ur hands do a lot: drawing, wigs, all those little details. let them be empty for a minute if they need it.",
    "put the thing u keep losing somewhere kind to future u. pencil, hair tie, charger. one tiny favour from today to tomorrow.",
    "a low-energy day doesn't need a high-energy explanation. u can simply have less to give today.",
    "the next lovely thing can be as small as changing into something comfortable. a whole new routine is not required.",
    "u don't have to finish using every spare minute. some minutes are allowed to remain wonderfully unassigned.",
    "before starting another big thing, check whether u actually want to or just feel like u should. ur answer matters.",
    "keep the music at a comfortable volume. ur favourite part will still be ur favourite part without needing to shake the furniture.",
    "a break doesn't have to produce a fresh idea to be worth taking. a break can simply be a break.",
    "ur messages can wait while u eat, rest or finish a thought. being reachable is not the same as being available.",
    "if tonight is turning into 'one more thing' on repeat, u can save the rest for tomorrow. even a good playlist has a pause button.",
    "make a little room around whatever u're working on. sometimes a clear patch of table is a very nice gift to urself.",
    "u're allowed an evening that nobody gets a finished drawing, funny reply or impressive story from. it can just belong to u.",
    "before leaving this little jar, maybe take one kind thing with u: a sip, a stretch if comfortable, or simply a less harsh thought about urself.",
  ]},
  { theme: "soft", label: "for a softer moment", feelings: ["sad", "overwhelmed"], notes: [
    "u don't have to find the bright side before getting a little care. this note can just sit with u where u are.",
    "the funny, talented parts of u haven't disappeared if they're quiet today. u don't have to perform them to keep them.",
    "a hard day doesn't make u a hard person to love. it makes this a good moment for a gentler little note.",
    "u can be disappointed without turning the disappointment into a description of who u are.",
    "not having the words yet is okay. ur feelings don't have to arrive as a beautifully edited paragraph.",
    "the drawing can wait. the replies can wait. u are allowed to be the person who needs looking after for a bit.",
    "u don't have to match the cheerful colours of this website. the lilac stays here for u on the grey-feeling days too.",
    "a favourite character, a familiar song, a comfortable seat. u can choose one small nice thing without asking it to fix everything.",
    "ur kindness isn't less real when u feel sad. a lovely person can have an unlovely afternoon.",
    "u can miss something without needing to replace it immediately. some feelings need a little space rather than a solution.",
    "there isn't a minimum amount of coping u have to demonstrate before deserving comfort.",
    "u don't need to apologise to this jar for pulling another note. wanting a little more reassurance is allowed.",
    "today doesn't have to become an inspiring comeback story. getting to the next quiet moment is enough of a plot for now.",
    "something going badly isn't proof that all the good things about u were pretend. the two stories don't cancel each other out.",
    "if being cheerful takes too much effort, u can stop auditioning for cheerful. u still belong here.",
    "u are more than the part of the day that hurt. the rest of u still deserves tenderness.",
    "a little encouragement doesn't have to be loud. here's the quiet version: u matter, even right now.",
    "u don't have to turn a feeling into a lesson before letting it pass. sometimes it can just be a feeling u had.",
    "a drawing left unfinished, a quiet playlist, a message for later. none of those things makes u a disappointment.",
    "if a familiar person feels safe to talk to, u can ask for company without having the perfect explanation ready.",
  ]},
  { theme: "steady", label: "one gentle thing at a time", feelings: ["anxious", "overwhelmed"], notes: [
    "u don't have to solve the whole day while sitting in this one moment. one small next thing is plenty to look at.",
    "a thought can be loud without knowing the future. u don't have to treat every worried possibility like a confirmed appointment.",
    "u can ask for the instructions again. needing clarity doesn't make u difficult.",
    "if everything feels equally urgent, u're allowed to pause before deciding what actually needs u first.",
    "a blank page offers a lot of possibilities. u only need one small mark to begin, and beginning is optional right now.",
    "u don't have to practise every possible conversation in advance to deserve a kind one.",
    "the version of u learning a difficult thing deserves encouragement too, not just the version that already knows how.",
    "u can make a plan with room to change it. flexibility isn't the same thing as failing to follow through.",
    "if a reply feels complicated, a simple 'i'll get back to u' is allowed. u don't owe an instant perfect sentence.",
    "not knowing something yet is a normal place for a curious person to be. even the interesting hobbies start there.",
    "pick the smaller version if it helps. one doodle, one song, one little cleared space. small isn't a dishonest way to begin.",
    "u are allowed to ask someone to explain what they meant instead of spending the evening trying to guess.",
    "a project can have a messy middle without being doomed. costumes and drawings are very familiar with the messy middle.",
    "the feeling of being behind doesn't have to choose the pace for the rest of ur day.",
    "u don't have to know what future u will want forever. today's small decision can be enough for today.",
    "ur brain doesn't need more tabs open just because another tab exists. a few can stay closed for now.",
    "if choosing is tiring, a familiar favourite is a perfectly good choice. the song u already know is still a song.",
    "u can prepare with care and still leave a little space for not knowing. certainty isn't the price of trying.",
    "being nervous doesn't erase ur skills. the artist, cosplayer and dancer in u don't leave because a feeling walked in.",
    "a gentle reminder: u don't have to be good at resting immediately either. there is no score for this part.",
  ]},
  { theme: "space", label: "a little room to breathe", feelings: ["angry", "overwhelmed"], notes: [
    "u can be angry and still be kind. kindness doesn't require pretending that nothing bothered u.",
    "u don't have to send the reply while it's still forming itself in all caps. ur words are allowed a waiting room.",
    "a little space is a reasonable request. u don't need a courtroom presentation to justify wanting it.",
    "ur quiet can mean 'i need a moment'. it doesn't have to mean anything more dramatic than that.",
    "the caring part of u can stay caring while the boundary stays firm. neither one has to lose.",
    "u are allowed to decide that a conversation can continue later. later is a real option on the menu.",
    "having less patience today doesn't erase all the times u've been thoughtful. one feeling doesn't rewrite ur whole character.",
    "this note has no requests, follow-up tasks or 'just one quick thing'. a rare and considerate visitor.",
    "u don't have to laugh something off if it didn't feel funny. ur reaction is allowed to have information in it.",
    "a boundary can be short. 'not today' is already a sentence.",
    "u can care about someone and still not be available for everything they want from u.",
    "if the day feels noisy, choosing a quieter corner is allowed. ur attention belongs to u.",
    "the jar is on a strict no-unsolicited-lecture policy. here's a little affection instead.",
    "u don't have to win every argument to keep ur dignity. deciding where ur energy goes is a choice too.",
    "being misunderstood can feel rough. u're still allowed to take time before finding the words to explain urself.",
    "u can have a soft spot for animals, characters and favourite songs while having absolutely no spare social battery.",
    "a difficult conversation doesn't get ownership of the whole evening. there's still room for something that belongs to u.",
    "u don't have to make ur frustration entertaining for anyone. it can be plain, unfunny and still worth hearing.",
    "ur next move can be a pause. extremely underrated plot development.",
    "this little world is still for u when u're not in the mood to be sweet about anything. come sit for a bit.",
  ]},
  { theme: "bright", label: "a little cheer just for u", feelings: ["happy", "excited", "content", "playful"], notes: [
    "a good mood doesn't need to be spent efficiently. u can just enjoy being in it for a while.",
    "if something small made u smile today, it gets to count. the happiness committee has no minimum-size rule.",
    "u can celebrate a little win before deciding what comes next. give it a moment to be a win.",
    "let a favourite song have the room for a minute. ur day is allowed a little soundtrack moment.",
    "u don't have to downplay being pleased with something u made. 'i like this' is such a nice sentence to get to say.",
    "there are so many interesting things u could enjoy making. today only needs to hold the ones u actually want.",
    "ur enthusiasm is one of the things that makes u special. liking something with ur whole heart is lovely to have in a person.",
    "a nice ordinary afternoon deserves to exist without a dramatic event attached. quiet happiness is still happiness.",
    "u can share a little excitement even if the thing seems niche. the tiny details are often the fun part.",
    "a happy thought is allowed to stay simple. it doesn't have to become a plan, a post or a promise.",
    "if u feel proud of urself today, let that feeling have a comfortable seat. it doesn't need to stand awkwardly in the doorway.",
    "ur favourite things are allowed to be a bit much. joy sometimes arrives with a very specific character name and several exclamation marks.",
    "a little adventure could be a new colour combination or a song u haven't tried. interesting doesn't always have to mean enormous.",
    "u can enjoy a peaceful moment without checking whether u've earned enough peace for it.",
    "the best kind of lovely detail is sometimes the one only u notice. u still get to enjoy it completely.",
    "today's note is a tiny cheer for being curious, creative and very much ur own person.",
    "a birthday gift can keep being a gift on an ordinary tuesday. the affection wasn't meant to expire when the candle went out.",
    "u deserve pleasant surprises that ask nothing back. consider this one folded neatly into a jar.",
    "being excited about ur next idea is a lovely feeling. u can enjoy imagining it before doing any of the work.",
    "a whole little world for ur art, songs, characters and humour. it makes sense that someone wanted to make space for all of u.",
  ]},
  { theme: "maomao", label: "a note from the apothecary", voice: "maomao", notes: [
    "Drawing, ballet, wig styling. You have a habit of choosing complicated work. Hm. I understand the appeal. Remember to put it down occasionally.",
    "An unfinished sketch is evidence of an idea in progress. It isn't a crime. Leave it on the table; you can return to it.",
    "You kept a whole little place for the things you enjoy. Sensible. People spend far too much time being embarrassed about having interests.",
    "I was told you're kind. Keep some of that patience for yourself. It would be an inefficient arrangement otherwise.",
    "Yes, you may sit here quietly. The mortar doesn't require conversation, and neither do I.",
    "The herbs can wait while you eat. I dislike admitting this, but even interesting work has to leave room for ordinary necessities.",
    "You can ask for help with the difficult part. It doesn't remove your name from the work.",
    "A mistake tells you something about the attempt. It tells you rather less about the person making it. Don't confuse the two.",
    "Another song? Fine. If the rhythm helps you enjoy your afternoon, that's a perfectly adequate reason.",
    "Not every useful observation is dramatic. Sometimes it is simply noticing that you're tired and putting the work away.",
    "Animals liking you is a pleasant recommendation. I wouldn't make a grand theory of it. I would enjoy their company.",
    "You style wigs. I sort specimens. A surprising amount of life comes down to patience with small, uncooperative things.",
    "If you want to examine something interesting for a little longer, do. Curiosity doesn't need to apologise for taking up a chair.",
    "You don't need to be impressive while taking a break. That would make it a rather badly designed break.",
    "A pretty result is nice. Understanding what you tried is useful too. You may keep both kinds of satisfaction.",
    "You can be fond of people and need them to stop talking for a moment. There. A simple observation. No contradiction.",
    "I have no new errand for you. Just this note. Try not to look so suspicious of a quiet moment.",
    "Your interests are your own. I wouldn't surrender a good herb collection merely because someone found it peculiar.",
    "Put the label on before you forget what you meant. Or save the drawing. Different desk, same practical problem.",
    "There is room for your things here. The drawings, the songs, the questions. Mind the jars, and make yourself comfortable.",
  ]},
];

export const NOTE_JAR_NOTES = groups.flatMap(({ notes, ...group }) => notes.map(text => ({
  id: createHash("sha256").update(text.normalize("NFKC").toLowerCase()).digest("hex").slice(0, 20),
  theme: group.theme, label: group.label, text,
  feelings: group.feelings ?? [], voice: group.voice ?? "bestie",
  byline: group.voice === "maomao" ? "a Maomao-inspired little note" : "✦ kiriya.love",
})));
