// PRIVATE. Explicit preferences from the approved September 15 pipeline, never inferred from clicks.
export const TASTE_DEFAULTS = {
  characters: {
    maomao: 1,
    "hatsune miku": 1,
    "kagamine rin": 0.8,
    "kagamine len": 0.8,
    luka: 0.5,
    kaito: 0.5,
    meiko: 0.5,
    "kasane teto": 0.5,
    gumi: 0.5,
  },
  companions: ["pairin", "meimei", "joka", "xiaolan", "gaoshun"],
  companionBonus: 0.2,
  voicebanks: {
    "hatsune miku": 1,
    "kagamine rin": 0.8,
    "kagamine len": 0.8,
    luka: 0.5,
    kaito: 0.5,
    meiko: 0.5,
    "kasane teto": 0.5,
    gumi: 0.5,
  },
  sekai: {
    server: "global",
    virtualSingers: 0.9,
    units: {
      "wonderlands×showtime": 0.6,
      "vivid bad squad": 0.6,
      "leo/need": 0.6,
    },
    otherUnits: 0.3,
    releasedOnly: true,
  },
  fandoms: {
    "project sekai": 0.7,
    "genshin impact": 0.7,
    "honkai: star rail": 0.7,
    frieren: 0.7,
    "witch hat atelier": 0.7,
    "bungo stray dogs": 0.7,
    "oshi no ko": 0.5,
    "bocchi the rock!": 0.5,
    "girls band cry": 0.5,
    minecraft: 0.4,
  },
  eras: ["classics 2007–2013", "modern hits", "rin & len story songs"],
  eraWeight: 0.8,
  newSongWeight: 0.7,
  producers: [],
  producerWindowDays: 7,
  maomaoMoments: [
    "poison",
    "herbs",
    "disgusted face",
    "case-solving",
    "verdigris house",
  ],
  momentBonus: 0.15,
  cosplayWishlist: [
    "snow miku",
    "sakura miku",
    "magical mirai miku",
    "sekai miku",
    "frieren",
    "witch hat atelier",
  ],
  wishlistBonus: 0.2,
  pastCosplays: ["maomao", "hatsune miku", "lynette"],
  skills: [
    "wig styling",
    "digital drawing",
    "traditional drawing",
    "ballet",
    "singing",
    "dancing",
  ],
  rotatingFandoms: [
    "project sekai",
    "genshin impact",
    "frieren",
    "witch hat atelier",
    "honkai: star rail",
    "bungo stray dogs",
    "music anime",
  ],
  events: [
    "afa singapore",
    "singapore comic con",
    "the apothecary diaries exhibition",
  ],
  fashion: ["y2k", "skater streetwear", "sweet", "girly"],
  merch: {
    minSgd: 30,
    maxSgd: 100,
    budgetBonus: 0.15,
    typeBonus: 0.1,
    types: [
      "acrylic stands",
      "badges",
      "nendoroids",
      "scale figures",
      "prize figures",
      "plushies",
      "shirts",
      "pins",
    ],
    shops: ["taobao", "local stores", "japanese shops"],
    shipsTo: "SG",
  },
  memeFormats: ["pov", "me_when", "text_post", "reaction", "unhinged fandom"],
  memeFormatBonus: 0.2,
  humor: ["relatable", "dark", "absurd"],
  minecraftMemesOnly: true,
  offLimits: [
    "explicit",
    "suggestive",
    "ai-generated art",
    "ai-assisted art",
    "gore",
    "horror images",
    "politics",
    "drama",
    "self-harm",
    "suicide",
    "family jokes",
    "body or appearance jokes",
    "sexual jokes about kiriya",
    "slurs",
  ],
  spoilers: "none",
  shipsAllowed: true,
  insideJokes: [],
};
