// Public compliments requested for Kiriya's cosplay portraits. No invented craft history.
const everyday = [
  "ur cosplay is cute. u make it unforgettable. ♡",
  "a whole favourite character, with ur own little magic",
  "u look so pretty in this little world of ur making",
  "the outfit is lovely. the person in it? even lovelier.",
  "cosplay suits ur creative little heart",
  "casually looking this cute should come with a warning",
  "a very pretty person with very good character taste",
  "this look has personality. so much of it is u.",
  "ur favourite characters look good on u",
  "somebody put a bow on this moment. oh wait, done. ♡",
  "u bring such a lovely spark to dressing up",
  "a little costume, a lot of charm",
  "the camera got lucky with this one",
  "ur cosplay deserves its own tiny fan club",
  "pretty, creative, and just a little bit of a menace",
  "u look like the nicest surprise in a photo album",
  "this is the kind of cute that makes me stop scrolling",
  "a favourite look on a favourite person",
  "ur character taste and ur cuteness make quite a team",
  "the details are lovely. ur presence makes the picture.",
  "u make playing dress-up look like an art form",
  "the prettiest little plot twist in the room",
  "ur cosplay has so much character, in every sense",
  "a tiny standing ovation for this entire look",
  "u look wonderful. yes, this caption is very biased.",
  "this photo deserves a little heart in the corner",
  "ur kind of pretty has so much personality",
  "the look is a whole mood. the mood is adorable.",
  "u add something special to every character u wear",
  "a little creativity looks very good on u",
  "this much charm in one frame is a bit unfair",
  "u look like the reason someone starts loving cosplay",
  "ur cosplay belongs on the favourite page",
  "a lovely look, worn by an even lovelier human",
  "the character is fictional. ur cuteness is very real.",
  "u have such a sweet way of making a look ur own",
  "this picture just earned another imaginary heart",
  "pretty enough to distract this caption from its job",
  "ur creative side is one of ur prettiest things",
  "a little appreciation for the person behind the cosplay",
  "u look like u stepped out of a very lovely daydream",
  "this outfit found exactly the right person",
  "the tiniest details make this look so lovely",
  "ur cosplay has main-character charm and ur own warmth",
  "a frame full of character. a person full of charm.",
  "u make ur favourite worlds feel a little closer",
  "this look is going straight into the cute folder",
  "ur outfit taste deserves a little round of applause",
  "just admiring how very u this whole picture feels",
  "the wig, the look, the lovely little person. excellent.",
  "u wear creativity so beautifully",
  "a very good look for a very special human",
  "ur cosplay is giving the photo album a favourite",
  "the little details make me want to look twice",
  "u make this character feel wonderfully alive",
  "a pretty picture of someone much more than pretty",
  "the outfit tells a story. u give it the personality.",
  "ur charm cannot be contained by one tiny frame",
  "this is a very cute use of imagination",
  "some looks are memorable because of who wears them",
  "u have excellent taste in becoming fictional people",
  "ur cosplay is a lovely excuse to admire u again",
  "the cute committee has reached a unanimous decision",
  "u look so lovely. the caption is simply reporting facts.",
  "a little round of applause for ur whole look",
  "ur favourite character got a very charming interpretation",
  "u bring the lovely little spark the costume can't supply",
  "this look and that face are an extremely cute combination",
  "a very pretty reminder of how creative u are",
  "ur cosplay makes this corner feel extra special",
  "the outfit is a favourite. u are the reason.",
  "a little heart for every lovely detail in this picture",
  "u could give this look its own opening credits",
  "this is what happens when good taste meets a cute face",
  "ur cosplay has officially improved the view",
  "looking this lovely is a very good side quest",
  "u make a fictional world feel a little more personal",
  "ur imagination deserves the same praise as ur pretty face",
  "this photo has an unreasonable amount of charm",
  "a little obsessed with how lovely u look here. ♡",
];

const cheekPose = [
  "that little hand-by-cheek pose is ridiculously cute",
  "ur smile is the sweetest detail in this cosplay",
  "maomao cosplay, with a little extra sunshine from u",
  "the green braids and that sweet smile? unfairly cute.",
  "this warm little photo has such a lovely smile in it",
  "a pretty apothecary with the cutest cheeky pose",
  "ur smile makes this whole costume feel even lovelier",
  "the pink robes are lovely. that little grin wins.",
  "a tiny smile, a favourite cosplay, a very cute moment",
  "maomao brought the look. u brought that lovely smile.",
];

const sleevePose = [
  "hiding behind a sleeve has never looked this cute",
  "that little side-eye is extremely maomao of u",
  "the pink sleeve reveal? a very pretty plot twist.",
  "green braids, gold earrings, and a lovely little glance",
  "a pretty apothecary with a suspiciously good side-eye",
  "that sleeve can only hide so much cuteness",
  "ur eyes make this shy little pose so charming",
  "the costume details and that glance work so beautifully",
  "a little mystery. a lot of very cute maomao energy.",
  "even half-hidden behind a sleeve, ur charm wins",
];

// The character portrait speaks for itself: Maomao addressing Kiriya, never praise for the drawing.
const floralPortrait = [
  "Your Maomao costume suited you. I don't say such things lightly.",
  "You draw, dance and style wigs. Hm. That is real patience.",
  "Your smile is pleasant. There. An observation, freely given.",
  "You made a place for the things you love. Sensible girl.",
  "Curiosity like yours is useful. Never apologise for it.",
  "They say you are kind. The evidence agrees with them.",
  "You notice small details. So do I. We would get along.",
  "A difficult sketch is still evidence of work. Keep it.",
  "Pretty, and interesting the moment she speaks. An unusual pair.",
  "You wear the braids better than the flowers suit me.",
  "Your enthusiasm is loud. I find it rather agreeable.",
  "You look after everyone. Put yourself on that list.",
  "Talent and patience, carried quietly. I notice both.",
  "You tend this little world of yours well. It shows.",
  "Rest when you need to. Even capable girls require it.",
  "Yes, you are worth the compliment. Don't make me repeat it.",
];

export const COSPLAY_PRAISE = [
  ...everyday.map(text => ({ text })),
  ...cheekPose.map(text => ({ text, photo: "img-5446" })),
  ...floralPortrait.map(text => ({ text, photo: "maomao-floral" })),
  // Kept with the retired IMG_5445: out of rotation, so this set stays unseen until that photo returns.
  ...sleevePose.map(text => ({ text, photo: "img-5445" })),
].map((item, index) => ({ id: `cosplay-praise-${String(index + 1).padStart(3, "0")}`, ...item }));
