// PRIVATE pool. "Maomao's herb cabinet": things from the series, with what's true in real life.
// Educational only. Nothing here is advice to taste, brew or apply anything.

const WPE = "https://en.wikipedia.org/wiki/List_of_The_Apothecary_Diaries_episodes";

export const herbs = [
  {
    id: "herb-lead-powder",
    name: "White lead face powder",
    kind: "poison",
    series: "The royal babies' “curse” in episode 1 was lead in the consorts' face powder.",
    real: "In 1923 researchers in Japan traced a deadly infant illness to lead in mothers' face powder. Lead white cosmetics were regulated there in the 1930s.",
    source: "https://cir.nii.ac.jp/crid/1390001206462024960",
    seriesSource: WPE,
  },
  {
    id: "herb-silver",
    name: "Silver tableware",
    kind: "myth",
    series: "Maomao recommends silver chopsticks and dishes for anyone worried about poison.",
    real: "Silver darkens when it touches sulfur compounds. The idea that it detects poison in general is mostly folklore.",
    source: "https://en.wikipedia.org/wiki/Silver",
    seriesSource: WPE,
  },
  {
    id: "herb-cacao",
    name: "Cacao",
    kind: "medicine",
    series: "Maomao's “dream assignment” was an aphrodisiac made from chocolate.",
    real: "A 2006 study found no link between chocolate and sexual function once age was taken into account. Tasty, though.",
    source: "https://pubmed.ncbi.nlm.nih.gov/16681473/",
    seriesSource: WPE,
  },
  {
    id: "herb-rhododendron",
    name: "Rhododendron",
    kind: "poison",
    series: "Her first warning was tied to a rhododendron, and its honey comes up again later.",
    real: "Rhododendrons contain grayanotoxins. “Mad honey” made from their nectar can drop blood pressure and slow the heart.",
    source: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3404272/",
    seriesSource: WPE,
  },
  {
    id: "herb-honey-babies",
    name: "Honey and babies",
    kind: "caution",
    series: "Honey given to a baby becomes part of a palace mystery.",
    real: "Babies under 12 months should never have honey, because of the risk of infant botulism.",
    source: "https://www.cdc.gov/botulism/prevention/index.html",
    seriesSource: WPE,
  },
  {
    id: "herb-aconite",
    name: "Aconite (wolfsbane)",
    kind: "poison",
    series: "Aconite turns up in the official Maomao no Hitorigoto shorts.",
    real: "Every part of aconite is toxic, the root most of all. Its aconitine affects the heart and nerves.",
    source: "https://www.poison.org/articles/why-is-monkshood-considered-a-poison--174",
    seriesSource: "https://kusuriya.fandom.com/wiki/The_Apothecary_Diaries_(Anime)/Mini_Episodes_S1",
  },
  {
    id: "herb-cordyceps",
    name: "Caterpillar fungus (冬虫夏草)",
    kind: "medicine",
    series: "Maomao keeps a treasured stash, and a season 2 episode title puns on its Japanese name.",
    real: "It grows out of ghost-moth caterpillars high on the Tibetan Plateau, around 4,000 m up, and is heavily overharvested.",
    source: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5432009/",
    seriesSource: WPE,
  },
  {
    id: "herb-pufferfish",
    name: "Pufferfish (tetrodotoxin)",
    kind: "poison",
    series: "Pufferfish comes up more than once, usually with Maomao looking far too interested.",
    real: "Tetrodotoxin blocks sodium channels in nerves. Cooking doesn't destroy it, and there's no antidote.",
    source: "https://www.ncbi.nlm.nih.gov/books/NBK507714/",
    seriesSource: WPE,
  },
  {
    id: "herb-seaweed",
    name: "Seaweed treated with limewater",
    kind: "caution",
    series: "A seaweed dish is only safe after the right treatment.",
    real: "Wild ogonori seaweed can stay toxic even after boiling. The kind sold in shops has been treated with alkali.",
    source: "https://www.pref.okayama.jp/page/detail-35141.html",
    seriesSource: WPE,
  },
  {
    id: "herb-datura",
    name: "Datura (曼荼羅華)",
    kind: "medicine",
    series: "Datura appears in both seasons.",
    real: "In 1804, Japanese surgeon Hanaoka Seishū used a Datura mixture for one of the first surgeries under general anaesthesia. Anaesthesiologists in Japan still use the flower as their logo.",
    source: "https://anesth.or.jp/users/english/about_jsa",
    seriesSource: WPE,
  },
  {
    id: "herb-bezoar",
    name: "Ox bezoar (牛黄)",
    kind: "medicine",
    series: "Jinshi's most effective bribe.",
    real: "Ox bezoar is a gallstone from cattle, used in traditional medicine for high fevers. Lab-cultured substitutes now exist.",
    source: "https://pubmed.ncbi.nlm.nih.gov/32068140/",
    seriesSource: WPE,
  },
  {
    id: "herb-flour-dust",
    name: "Flour dust",
    kind: "caution",
    series: "Maomao solves a mystery fire that was really a dust explosion.",
    real: "Fine food dusts can explode. A sugar dust explosion at a refinery in Georgia, USA, killed 14 people in 2008.",
    source: "https://en.wikipedia.org/wiki/2008_Georgia_Imperial_Sugar_refinery_explosion",
    seriesSource: WPE,
  },
  {
    id: "herb-blue-rose",
    name: "Blue roses",
    kind: "curiosity",
    series: "Maomao fakes out-of-season blue roses for a banquet.",
    real: "Roses can't make delphinidin, the pigment behind blue flowers. A gene-edited “blue” rose went on sale in Japan in 2009.",
    source: "https://phys.org/news/2009-10-blue-roses-debut-japan.html",
    seriesSource: WPE,
  },
  {
    id: "herb-balsam",
    name: "Balsam",
    kind: "curiosity",
    series: "Balsam gives an important season 1 episode its title.",
    real: "In China and Korea, balsam petals crushed with alum have long been used as an orange nail dye.",
    source: "https://en.wikipedia.org/wiki/Impatiens_balsamina",
    seriesSource: WPE,
  },
  {
    id: "herb-pheromones",
    name: "Moth pheromones",
    kind: "curiosity",
    series: "A “moon fairy” sighting is really moths drawn to a scent.",
    real: "Bombykol was the first pheromone ever identified, in 1959. It took about 500,000 silk moths to collect 6.4 mg of it.",
    source: "https://edu.rsc.org/feature/in-pursuit-of-bombykol/2020169.article",
    seriesSource: WPE,
  },
  {
    id: "herb-orpiment",
    name: "Orpiment",
    kind: "poison",
    series: "A late emperor's secret painting habit explains a very strange mystery.",
    real: "Orpiment means “gold pigment.” It's arsenic sulfide: bright, poisonous, and it reacts badly with lead and copper pigments.",
    source: "https://colourlex.com/project/orpiment/",
    seriesSource: WPE,
  },
  {
    id: "herb-mugwort",
    name: "Mugwort",
    kind: "medicine",
    series: "Mugwort and moxibustion come up in season 2.",
    real: "Moxa, the material burned in moxibustion, is aged and ground mugwort.",
    source: "https://en.wikipedia.org/wiki/Moxibustion",
    seriesSource: WPE,
  },
  {
    id: "herb-calico",
    name: "Calico cats",
    kind: "curiosity",
    series: "Maomao the cat is a calico.",
    real: "Calico cats are almost always female, because the orange and black coat genes sit on the X chromosome.",
    source: "https://www.bio.miami.edu/dana/dox/calico.html",
    seriesSource: "https://kusuriya.fandom.com/wiki/Maomao,_the_Cat",
  },
];
